title: "Phuoc Dang"
description: "Data Analytics Engineer | AI Enthusiast | Cloud Native Builder"

# Use custom layouts and styles
sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
